routes:
  /login:
    service: servico1
    secure: false
    circuit_breaker: DefaultCircuitBreaker
  /authenticate:
    service: servico1
    secure: false
    circuit_breaker: DefaultCircuitBreaker
  /summary:
    service: servico1
    secure: true
    circuit_breaker: DefaultCircuitBreaker
    