routes:
  /login:
    services: servico1
    secure: false
    circuit_breaker: DefaultCircuitBreaker
  /authenticate:
    services: servico1
    secure: false
    circuit_breaker: DefaultCircuitBreaker
  /summary:
    services: servico1
    secure: true
    circuit_breaker: DefaultCircuitBreaker
    